site_name: Mercach
site_url: https://marcovegar.github.io/mercach
site_description: Sistema administrativo para la gestión de locales y espacios abiertos del Mercado de Chacao. Manual de Usuario y Guía Técnica.
repo_url: https://github.com/MarcoVegaR/mercach
repo_name: MarcoVegaR/mercach
edit_uri: edit/main/docs/

strict: true

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.tabs.link

plugins:
  - search
  - tags
  - i18n:
      languages:
        - locale: es
          name: Español
          default: true
          build: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      type: timeago
  - glightbox
  - redirects:
      redirect_maps:
        permissions.md: how-to/permisos-permission-first.md
        auditing-logging.md: explanations/auditoria-vs-logging.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight
  - md_in_html

not_in_nav: |
  /CHANGELOG.md
  /backend/show-pattern.md
  /frontend/show-pattern.md

nav:
  - Inicio: index.md
  - Acerca:
      - Visión y objetivo: acerca/vision-objetivo.md
      - Alcance por fases: acerca/alcance.md
  - Procesos de negocio:
      - Introducción: procesos/index.md
      - Reglas de negocio: procesos/reglas-negocio.md
      - Generación de cargos: procesos/generacion-de-cargos.md
      - Pagos y recibos: procesos/pagos-y-recibos.md
  - Manual de usuario:
      - Introducción: user-manual/index.md
      - Mercados:
          - Visión general: user-manual/mercados/overview.md
          - Tareas: user-manual/mercados/tareas.md
      - Locales:
          - Visión general: user-manual/locales/overview.md
          - Tareas: user-manual/locales/tareas.md
          - FAQ: user-manual/locales/faq.md
      - Concesionarios:
          - Visión general: user-manual/concesionarios/overview.md
          - Tareas: user-manual/concesionarios/tareas.md
      - Contratos:
          - Visión general: user-manual/contratos/overview.md
          - Tareas: user-manual/contratos/tareas.md
      - Tarifas:
          - Visión general: user-manual/tarifas/overview.md
      - Cargos:
          - Visión general: user-manual/cargos/overview.md
      - Pagos:
          - Visión general: user-manual/pagos/overview.md
          - Tareas: user-manual/pagos/tareas.md
          - FAQ: user-manual/pagos/faq.md
      - Recibos:
          - Visión general: user-manual/recibos/overview.md
      - Portal:
          - Visión general: user-manual/portal/overview.md
      - Usuarios:
          - Visión general: user-manual/usuarios/overview.md
          - Tareas: user-manual/usuarios/tareas.md
          - FAQ: user-manual/usuarios/faq.md
      - Roles & Permisos:
          - Visión general: user-manual/roles-permisos/overview.md
          - Tareas: user-manual/roles-permisos/tareas.md
          - FAQ: user-manual/roles-permisos/faq.md
      - Settings:
          - Visión general: user-manual/settings/overview.md
          - Seguridad: user-manual/settings/seguridad.md
          - FAQ: user-manual/settings/faq.md
      - Auditoría:
          - Visión general: user-manual/auditoria/overview.md
          - Tareas: user-manual/auditoria/tareas.md
          - FAQ: user-manual/auditoria/faq.md
  - Guía técnica:
      - Introducción: operacion/index.md
      - Instalación y requisitos: operacion/instalacion.md
      - Configuración inicial: operacion/configuracion.md
      - Seguridad y acceso: operacion/seguridad.md
      - Operación y mantenimiento: operacion/mantenimiento.md
      - Respaldo y recuperación: operacion/respaldo.md
      - Soporte y escalamiento: operacion/soporte.md
  - Próximamente (v2):
      - Espacios abiertos:
          - Visión general: user-manual/espacios-abiertos/overview.md
          - Tareas: user-manual/espacios-abiertos/tareas.md
          - FAQ: user-manual/espacios-abiertos/faq.md
  - Apéndice:
      - Referencia:
          - Variables y permisos: reference/variables-y-permisos.md
          - Localización por defecto (ES): reference/localizacion-por-defecto.md
          - DataTable API: reference/datatable-api.md
          - Gestión de Roles: reference/roles-management.md
          - Accesibilidad: reference/accessibility.md
          - Buenas prácticas de rendimiento: reference/performance.md
      - Explicaciones:
          - Auditoría vs logging: explanations/auditoria-vs-logging.md
      - Módulos:
          - Auditoría: modules/auditoria.md
          - Usuarios: modules/users.md
      - Desarrollo:
          - CI/CD: ci-cd.md
          - Contribución: contributing.md
          - Cloudflare Tunnel (dev): how-to/cloudflare-tunnel-dev.md
          - Crear módulo Index: how-to/create-index-module.md
          - Generar catálogos (make:catalog): how-to/make-catalog.md
          - Registro de usuarios deshabilitado (admin-only): how-to/registro-usuarios-deshabilitado.md
          - Autoeliminación de cuenta deshabilitada: how-to/autoeliminacion-cuenta-deshabilitada.md
          - Validación de formularios (frontend): frontend/forms-validation.md
          - Formularios de Roles: frontend/roles-forms.md
          - Migas de pan (SPA): frontend/breadcrumbs.md
          - Footer (frontend): frontend/footer.md
  - Legal:
      - Términos de uso: legal/terminos.md
      - Privacidad: legal/privacidad.md
