<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Catalog Routes
|--------------------------------------------------------------------------
|
| This file is reserved for catalog-like resources generated by the
| make:catalog command. The generator will append new route groups here in
| an idempotent way. Keeping all catalogs in a single file simplifies
| maintenance and route discovery.
|
*/

// Marker: BEGIN AUTO-GENERATED CATALOG ROUTES (make:catalog)

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/local-type', [\App\Http\Controllers\LocalTypeController::class, 'index'])->middleware('permission:catalogs.local-type.view')->name('catalogs.local-type.index');
    Route::get('/catalogs/local-type/create', [\App\Http\Controllers\LocalTypeController::class, 'create'])->middleware('permission:catalogs.local-type.create')->name('catalogs.local-type.create');
    Route::post('/catalogs/local-type', [\App\Http\Controllers\LocalTypeController::class, 'store'])->middleware('permission:catalogs.local-type.create')->name('catalogs.local-type.store');
    Route::get('/catalogs/local-type/export', [\App\Http\Controllers\LocalTypeController::class, 'export'])->middleware('permission:catalogs.local-type.export')->name('catalogs.local-type.export');
    Route::post('/catalogs/local-type/bulk', [\App\Http\Controllers\LocalTypeController::class, 'bulk'])->middleware('permission:catalogs.local-type.delete|catalogs.local-type.restore|catalogs.local-type.forceDelete|catalogs.local-type.setActive')->name('catalogs.local-type.bulk');
    Route::get('/catalogs/local-type/selected', [\App\Http\Controllers\LocalTypeController::class, 'selected'])->middleware('permission:catalogs.local-type.view')->name('catalogs.local-type.selected');
    Route::get('/catalogs/local-type/{local_type}', [\App\Http\Controllers\LocalTypeController::class, 'show'])->middleware('permission:catalogs.local-type.view')->name('catalogs.local-type.show');
    Route::get('/catalogs/local-type/{local_type}/edit', [\App\Http\Controllers\LocalTypeController::class, 'edit'])->middleware('permission:catalogs.local-type.update')->name('catalogs.local-type.edit');
    Route::put('/catalogs/local-type/{local_type}', [\App\Http\Controllers\LocalTypeController::class, 'update'])->middleware('permission:catalogs.local-type.update')->name('catalogs.local-type.update');
    Route::patch('/catalogs/local-type/{local_type}/active', [\App\Http\Controllers\LocalTypeController::class, 'setActive'])->middleware('permission:catalogs.local-type.setActive')->name('catalogs.local-type.setActive');
    Route::delete('/catalogs/local-type/{local_type}', [\App\Http\Controllers\LocalTypeController::class, 'destroy'])->middleware('permission:catalogs.local-type.delete')->name('catalogs.local-type.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/local-status', [\App\Http\Controllers\LocalStatusController::class, 'index'])->middleware('permission:catalogs.local-status.view')->name('catalogs.local-status.index');
    Route::get('/catalogs/local-status/create', [\App\Http\Controllers\LocalStatusController::class, 'create'])->middleware('permission:catalogs.local-status.create')->name('catalogs.local-status.create');
    Route::post('/catalogs/local-status', [\App\Http\Controllers\LocalStatusController::class, 'store'])->middleware('permission:catalogs.local-status.create')->name('catalogs.local-status.store');
    Route::get('/catalogs/local-status/export', [\App\Http\Controllers\LocalStatusController::class, 'export'])->middleware('permission:catalogs.local-status.export')->name('catalogs.local-status.export');
    Route::post('/catalogs/local-status/bulk', [\App\Http\Controllers\LocalStatusController::class, 'bulk'])->middleware('permission:catalogs.local-status.delete|catalogs.local-status.restore|catalogs.local-status.forceDelete|catalogs.local-status.setActive')->name('catalogs.local-status.bulk');
    Route::get('/catalogs/local-status/selected', [\App\Http\Controllers\LocalStatusController::class, 'selected'])->middleware('permission:catalogs.local-status.view')->name('catalogs.local-status.selected');
    Route::get('/catalogs/local-status/{local_status}', [\App\Http\Controllers\LocalStatusController::class, 'show'])->middleware('permission:catalogs.local-status.view')->name('catalogs.local-status.show');
    Route::get('/catalogs/local-status/{local_status}/edit', [\App\Http\Controllers\LocalStatusController::class, 'edit'])->middleware('permission:catalogs.local-status.update')->name('catalogs.local-status.edit');
    Route::put('/catalogs/local-status/{local_status}', [\App\Http\Controllers\LocalStatusController::class, 'update'])->middleware('permission:catalogs.local-status.update')->name('catalogs.local-status.update');
    Route::patch('/catalogs/local-status/{local_status}/active', [\App\Http\Controllers\LocalStatusController::class, 'setActive'])->middleware('permission:catalogs.local-status.setActive')->name('catalogs.local-status.setActive');
    Route::delete('/catalogs/local-status/{local_status}', [\App\Http\Controllers\LocalStatusController::class, 'destroy'])->middleware('permission:catalogs.local-status.delete')->name('catalogs.local-status.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/trade-category', [\App\Http\Controllers\TradeCategoryController::class, 'index'])->middleware('permission:catalogs.trade-category.view')->name('catalogs.trade-category.index');
    Route::get('/catalogs/trade-category/create', [\App\Http\Controllers\TradeCategoryController::class, 'create'])->middleware('permission:catalogs.trade-category.create')->name('catalogs.trade-category.create');
    Route::post('/catalogs/trade-category', [\App\Http\Controllers\TradeCategoryController::class, 'store'])->middleware('permission:catalogs.trade-category.create')->name('catalogs.trade-category.store');
    Route::get('/catalogs/trade-category/export', [\App\Http\Controllers\TradeCategoryController::class, 'export'])->middleware('permission:catalogs.trade-category.export')->name('catalogs.trade-category.export');
    Route::post('/catalogs/trade-category/bulk', [\App\Http\Controllers\TradeCategoryController::class, 'bulk'])->middleware('permission:catalogs.trade-category.delete|catalogs.trade-category.restore|catalogs.trade-category.forceDelete|catalogs.trade-category.setActive')->name('catalogs.trade-category.bulk');
    Route::get('/catalogs/trade-category/selected', [\App\Http\Controllers\TradeCategoryController::class, 'selected'])->middleware('permission:catalogs.trade-category.view')->name('catalogs.trade-category.selected');
    Route::get('/catalogs/trade-category/{trade_category}', [\App\Http\Controllers\TradeCategoryController::class, 'show'])->middleware('permission:catalogs.trade-category.view')->name('catalogs.trade-category.show');
    Route::get('/catalogs/trade-category/{trade_category}/edit', [\App\Http\Controllers\TradeCategoryController::class, 'edit'])->middleware('permission:catalogs.trade-category.update')->name('catalogs.trade-category.edit');
    Route::put('/catalogs/trade-category/{trade_category}', [\App\Http\Controllers\TradeCategoryController::class, 'update'])->middleware('permission:catalogs.trade-category.update')->name('catalogs.trade-category.update');
    Route::patch('/catalogs/trade-category/{trade_category}/active', [\App\Http\Controllers\TradeCategoryController::class, 'setActive'])->middleware('permission:catalogs.trade-category.setActive')->name('catalogs.trade-category.setActive');
    Route::delete('/catalogs/trade-category/{trade_category}', [\App\Http\Controllers\TradeCategoryController::class, 'destroy'])->middleware('permission:catalogs.trade-category.delete')->name('catalogs.trade-category.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/concessionaire-type', [\App\Http\Controllers\ConcessionaireTypeController::class, 'index'])->middleware('permission:catalogs.concessionaire-type.view')->name('catalogs.concessionaire-type.index');
    Route::get('/catalogs/concessionaire-type/create', [\App\Http\Controllers\ConcessionaireTypeController::class, 'create'])->middleware('permission:catalogs.concessionaire-type.create')->name('catalogs.concessionaire-type.create');
    Route::post('/catalogs/concessionaire-type', [\App\Http\Controllers\ConcessionaireTypeController::class, 'store'])->middleware('permission:catalogs.concessionaire-type.create')->name('catalogs.concessionaire-type.store');
    Route::get('/catalogs/concessionaire-type/export', [\App\Http\Controllers\ConcessionaireTypeController::class, 'export'])->middleware('permission:catalogs.concessionaire-type.export')->name('catalogs.concessionaire-type.export');
    Route::post('/catalogs/concessionaire-type/bulk', [\App\Http\Controllers\ConcessionaireTypeController::class, 'bulk'])->middleware('permission:catalogs.concessionaire-type.delete|catalogs.concessionaire-type.restore|catalogs.concessionaire-type.forceDelete|catalogs.concessionaire-type.setActive')->name('catalogs.concessionaire-type.bulk');
    Route::get('/catalogs/concessionaire-type/selected', [\App\Http\Controllers\ConcessionaireTypeController::class, 'selected'])->middleware('permission:catalogs.concessionaire-type.view')->name('catalogs.concessionaire-type.selected');
    Route::get('/catalogs/concessionaire-type/{concessionaire_type}', [\App\Http\Controllers\ConcessionaireTypeController::class, 'show'])->middleware('permission:catalogs.concessionaire-type.view')->name('catalogs.concessionaire-type.show');
    Route::get('/catalogs/concessionaire-type/{concessionaire_type}/edit', [\App\Http\Controllers\ConcessionaireTypeController::class, 'edit'])->middleware('permission:catalogs.concessionaire-type.update')->name('catalogs.concessionaire-type.edit');
    Route::put('/catalogs/concessionaire-type/{concessionaire_type}', [\App\Http\Controllers\ConcessionaireTypeController::class, 'update'])->middleware('permission:catalogs.concessionaire-type.update')->name('catalogs.concessionaire-type.update');
    Route::patch('/catalogs/concessionaire-type/{concessionaire_type}/active', [\App\Http\Controllers\ConcessionaireTypeController::class, 'setActive'])->middleware('permission:catalogs.concessionaire-type.setActive')->name('catalogs.concessionaire-type.setActive');
    Route::delete('/catalogs/concessionaire-type/{concessionaire_type}', [\App\Http\Controllers\ConcessionaireTypeController::class, 'destroy'])->middleware('permission:catalogs.concessionaire-type.delete')->name('catalogs.concessionaire-type.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/document-type', [\App\Http\Controllers\DocumentTypeController::class, 'index'])->middleware('permission:catalogs.document-type.view')->name('catalogs.document-type.index');
    Route::get('/catalogs/document-type/create', [\App\Http\Controllers\DocumentTypeController::class, 'create'])->middleware('permission:catalogs.document-type.create')->name('catalogs.document-type.create');
    Route::post('/catalogs/document-type', [\App\Http\Controllers\DocumentTypeController::class, 'store'])->middleware('permission:catalogs.document-type.create')->name('catalogs.document-type.store');
    Route::get('/catalogs/document-type/export', [\App\Http\Controllers\DocumentTypeController::class, 'export'])->middleware('permission:catalogs.document-type.export')->name('catalogs.document-type.export');
    Route::post('/catalogs/document-type/bulk', [\App\Http\Controllers\DocumentTypeController::class, 'bulk'])->middleware('permission:catalogs.document-type.delete|catalogs.document-type.restore|catalogs.document-type.forceDelete|catalogs.document-type.setActive')->name('catalogs.document-type.bulk');
    Route::get('/catalogs/document-type/selected', [\App\Http\Controllers\DocumentTypeController::class, 'selected'])->middleware('permission:catalogs.document-type.view')->name('catalogs.document-type.selected');
    Route::get('/catalogs/document-type/{document_type}', [\App\Http\Controllers\DocumentTypeController::class, 'show'])->middleware('permission:catalogs.document-type.view')->name('catalogs.document-type.show');
    Route::get('/catalogs/document-type/{document_type}/edit', [\App\Http\Controllers\DocumentTypeController::class, 'edit'])->middleware('permission:catalogs.document-type.update')->name('catalogs.document-type.edit');
    Route::put('/catalogs/document-type/{document_type}', [\App\Http\Controllers\DocumentTypeController::class, 'update'])->middleware('permission:catalogs.document-type.update')->name('catalogs.document-type.update');
    Route::patch('/catalogs/document-type/{document_type}/active', [\App\Http\Controllers\DocumentTypeController::class, 'setActive'])->middleware('permission:catalogs.document-type.setActive')->name('catalogs.document-type.setActive');
    Route::delete('/catalogs/document-type/{document_type}', [\App\Http\Controllers\DocumentTypeController::class, 'destroy'])->middleware('permission:catalogs.document-type.delete')->name('catalogs.document-type.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/contract-type', [\App\Http\Controllers\ContractTypeController::class, 'index'])->middleware('permission:catalogs.contract-type.view')->name('catalogs.contract-type.index');
    Route::get('/catalogs/contract-type/create', [\App\Http\Controllers\ContractTypeController::class, 'create'])->middleware('permission:catalogs.contract-type.create')->name('catalogs.contract-type.create');
    Route::post('/catalogs/contract-type', [\App\Http\Controllers\ContractTypeController::class, 'store'])->middleware('permission:catalogs.contract-type.create')->name('catalogs.contract-type.store');
    Route::get('/catalogs/contract-type/export', [\App\Http\Controllers\ContractTypeController::class, 'export'])->middleware('permission:catalogs.contract-type.export')->name('catalogs.contract-type.export');
    Route::post('/catalogs/contract-type/bulk', [\App\Http\Controllers\ContractTypeController::class, 'bulk'])->middleware('permission:catalogs.contract-type.delete|catalogs.contract-type.restore|catalogs.contract-type.forceDelete|catalogs.contract-type.setActive')->name('catalogs.contract-type.bulk');
    Route::get('/catalogs/contract-type/selected', [\App\Http\Controllers\ContractTypeController::class, 'selected'])->middleware('permission:catalogs.contract-type.view')->name('catalogs.contract-type.selected');
    Route::get('/catalogs/contract-type/{contract_type}', [\App\Http\Controllers\ContractTypeController::class, 'show'])->middleware('permission:catalogs.contract-type.view')->name('catalogs.contract-type.show');
    Route::get('/catalogs/contract-type/{contract_type}/edit', [\App\Http\Controllers\ContractTypeController::class, 'edit'])->middleware('permission:catalogs.contract-type.update')->name('catalogs.contract-type.edit');
    Route::put('/catalogs/contract-type/{contract_type}', [\App\Http\Controllers\ContractTypeController::class, 'update'])->middleware('permission:catalogs.contract-type.update')->name('catalogs.contract-type.update');
    Route::patch('/catalogs/contract-type/{contract_type}/active', [\App\Http\Controllers\ContractTypeController::class, 'setActive'])->middleware('permission:catalogs.contract-type.setActive')->name('catalogs.contract-type.setActive');
    Route::delete('/catalogs/contract-type/{contract_type}', [\App\Http\Controllers\ContractTypeController::class, 'destroy'])->middleware('permission:catalogs.contract-type.delete')->name('catalogs.contract-type.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/contract-status', [\App\Http\Controllers\ContractStatusController::class, 'index'])->middleware('permission:catalogs.contract-status.view')->name('catalogs.contract-status.index');
    Route::get('/catalogs/contract-status/create', [\App\Http\Controllers\ContractStatusController::class, 'create'])->middleware('permission:catalogs.contract-status.create')->name('catalogs.contract-status.create');
    Route::post('/catalogs/contract-status', [\App\Http\Controllers\ContractStatusController::class, 'store'])->middleware('permission:catalogs.contract-status.create')->name('catalogs.contract-status.store');
    Route::get('/catalogs/contract-status/export', [\App\Http\Controllers\ContractStatusController::class, 'export'])->middleware('permission:catalogs.contract-status.export')->name('catalogs.contract-status.export');
    Route::post('/catalogs/contract-status/bulk', [\App\Http\Controllers\ContractStatusController::class, 'bulk'])->middleware('permission:catalogs.contract-status.delete|catalogs.contract-status.restore|catalogs.contract-status.forceDelete|catalogs.contract-status.setActive')->name('catalogs.contract-status.bulk');
    Route::get('/catalogs/contract-status/selected', [\App\Http\Controllers\ContractStatusController::class, 'selected'])->middleware('permission:catalogs.contract-status.view')->name('catalogs.contract-status.selected');
    Route::get('/catalogs/contract-status/{contract_status}', [\App\Http\Controllers\ContractStatusController::class, 'show'])->middleware('permission:catalogs.contract-status.view')->name('catalogs.contract-status.show');
    Route::get('/catalogs/contract-status/{contract_status}/edit', [\App\Http\Controllers\ContractStatusController::class, 'edit'])->middleware('permission:catalogs.contract-status.update')->name('catalogs.contract-status.edit');
    Route::put('/catalogs/contract-status/{contract_status}', [\App\Http\Controllers\ContractStatusController::class, 'update'])->middleware('permission:catalogs.contract-status.update')->name('catalogs.contract-status.update');
    Route::patch('/catalogs/contract-status/{contract_status}/active', [\App\Http\Controllers\ContractStatusController::class, 'setActive'])->middleware('permission:catalogs.contract-status.setActive')->name('catalogs.contract-status.setActive');
    Route::delete('/catalogs/contract-status/{contract_status}', [\App\Http\Controllers\ContractStatusController::class, 'destroy'])->middleware('permission:catalogs.contract-status.delete')->name('catalogs.contract-status.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/contract-modality', [\App\Http\Controllers\ContractModalityController::class, 'index'])->middleware('permission:catalogs.contract-modality.view')->name('catalogs.contract-modality.index');
    Route::get('/catalogs/contract-modality/create', [\App\Http\Controllers\ContractModalityController::class, 'create'])->middleware('permission:catalogs.contract-modality.create')->name('catalogs.contract-modality.create');
    Route::post('/catalogs/contract-modality', [\App\Http\Controllers\ContractModalityController::class, 'store'])->middleware('permission:catalogs.contract-modality.create')->name('catalogs.contract-modality.store');
    Route::get('/catalogs/contract-modality/export', [\App\Http\Controllers\ContractModalityController::class, 'export'])->middleware('permission:catalogs.contract-modality.export')->name('catalogs.contract-modality.export');
    Route::post('/catalogs/contract-modality/bulk', [\App\Http\Controllers\ContractModalityController::class, 'bulk'])->middleware('permission:catalogs.contract-modality.delete|catalogs.contract-modality.restore|catalogs.contract-modality.forceDelete|catalogs.contract-modality.setActive')->name('catalogs.contract-modality.bulk');
    Route::get('/catalogs/contract-modality/selected', [\App\Http\Controllers\ContractModalityController::class, 'selected'])->middleware('permission:catalogs.contract-modality.view')->name('catalogs.contract-modality.selected');
    Route::get('/catalogs/contract-modality/{contract_modality}', [\App\Http\Controllers\ContractModalityController::class, 'show'])->middleware('permission:catalogs.contract-modality.view')->name('catalogs.contract-modality.show');
    Route::get('/catalogs/contract-modality/{contract_modality}/edit', [\App\Http\Controllers\ContractModalityController::class, 'edit'])->middleware('permission:catalogs.contract-modality.update')->name('catalogs.contract-modality.edit');
    Route::put('/catalogs/contract-modality/{contract_modality}', [\App\Http\Controllers\ContractModalityController::class, 'update'])->middleware('permission:catalogs.contract-modality.update')->name('catalogs.contract-modality.update');
    Route::patch('/catalogs/contract-modality/{contract_modality}/active', [\App\Http\Controllers\ContractModalityController::class, 'setActive'])->middleware('permission:catalogs.contract-modality.setActive')->name('catalogs.contract-modality.setActive');
    Route::delete('/catalogs/contract-modality/{contract_modality}', [\App\Http\Controllers\ContractModalityController::class, 'destroy'])->middleware('permission:catalogs.contract-modality.delete')->name('catalogs.contract-modality.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/expense-type', [\App\Http\Controllers\ExpenseTypeController::class, 'index'])->middleware('permission:catalogs.expense-type.view')->name('catalogs.expense-type.index');
    Route::get('/catalogs/expense-type/create', [\App\Http\Controllers\ExpenseTypeController::class, 'create'])->middleware('permission:catalogs.expense-type.create')->name('catalogs.expense-type.create');
    Route::post('/catalogs/expense-type', [\App\Http\Controllers\ExpenseTypeController::class, 'store'])->middleware('permission:catalogs.expense-type.create')->name('catalogs.expense-type.store');
    Route::get('/catalogs/expense-type/export', [\App\Http\Controllers\ExpenseTypeController::class, 'export'])->middleware('permission:catalogs.expense-type.export')->name('catalogs.expense-type.export');
    Route::post('/catalogs/expense-type/bulk', [\App\Http\Controllers\ExpenseTypeController::class, 'bulk'])->middleware('permission:catalogs.expense-type.delete|catalogs.expense-type.restore|catalogs.expense-type.forceDelete|catalogs.expense-type.setActive')->name('catalogs.expense-type.bulk');
    Route::get('/catalogs/expense-type/selected', [\App\Http\Controllers\ExpenseTypeController::class, 'selected'])->middleware('permission:catalogs.expense-type.view')->name('catalogs.expense-type.selected');
    Route::get('/catalogs/expense-type/{expense_type}', [\App\Http\Controllers\ExpenseTypeController::class, 'show'])->middleware('permission:catalogs.expense-type.view')->name('catalogs.expense-type.show');
    Route::get('/catalogs/expense-type/{expense_type}/edit', [\App\Http\Controllers\ExpenseTypeController::class, 'edit'])->middleware('permission:catalogs.expense-type.update')->name('catalogs.expense-type.edit');
    Route::put('/catalogs/expense-type/{expense_type}', [\App\Http\Controllers\ExpenseTypeController::class, 'update'])->middleware('permission:catalogs.expense-type.update')->name('catalogs.expense-type.update');
    Route::patch('/catalogs/expense-type/{expense_type}/active', [\App\Http\Controllers\ExpenseTypeController::class, 'setActive'])->middleware('permission:catalogs.expense-type.setActive')->name('catalogs.expense-type.setActive');
    Route::delete('/catalogs/expense-type/{expense_type}', [\App\Http\Controllers\ExpenseTypeController::class, 'destroy'])->middleware('permission:catalogs.expense-type.delete')->name('catalogs.expense-type.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/payment-status', [\App\Http\Controllers\PaymentStatusController::class, 'index'])->middleware('permission:catalogs.payment-status.view')->name('catalogs.payment-status.index');
    Route::get('/catalogs/payment-status/create', [\App\Http\Controllers\PaymentStatusController::class, 'create'])->middleware('permission:catalogs.payment-status.create')->name('catalogs.payment-status.create');
    Route::post('/catalogs/payment-status', [\App\Http\Controllers\PaymentStatusController::class, 'store'])->middleware('permission:catalogs.payment-status.create')->name('catalogs.payment-status.store');
    Route::get('/catalogs/payment-status/export', [\App\Http\Controllers\PaymentStatusController::class, 'export'])->middleware('permission:catalogs.payment-status.export')->name('catalogs.payment-status.export');
    Route::post('/catalogs/payment-status/bulk', [\App\Http\Controllers\PaymentStatusController::class, 'bulk'])->middleware('permission:catalogs.payment-status.delete|catalogs.payment-status.restore|catalogs.payment-status.forceDelete|catalogs.payment-status.setActive')->name('catalogs.payment-status.bulk');
    Route::get('/catalogs/payment-status/selected', [\App\Http\Controllers\PaymentStatusController::class, 'selected'])->middleware('permission:catalogs.payment-status.view')->name('catalogs.payment-status.selected');
    Route::get('/catalogs/payment-status/{payment_status}', [\App\Http\Controllers\PaymentStatusController::class, 'show'])->middleware('permission:catalogs.payment-status.view')->name('catalogs.payment-status.show');
    Route::get('/catalogs/payment-status/{payment_status}/edit', [\App\Http\Controllers\PaymentStatusController::class, 'edit'])->middleware('permission:catalogs.payment-status.update')->name('catalogs.payment-status.edit');
    Route::put('/catalogs/payment-status/{payment_status}', [\App\Http\Controllers\PaymentStatusController::class, 'update'])->middleware('permission:catalogs.payment-status.update')->name('catalogs.payment-status.update');
    Route::patch('/catalogs/payment-status/{payment_status}/active', [\App\Http\Controllers\PaymentStatusController::class, 'setActive'])->middleware('permission:catalogs.payment-status.setActive')->name('catalogs.payment-status.setActive');
    Route::delete('/catalogs/payment-status/{payment_status}', [\App\Http\Controllers\PaymentStatusController::class, 'destroy'])->middleware('permission:catalogs.payment-status.delete')->name('catalogs.payment-status.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/bank', [\App\Http\Controllers\BankController::class, 'index'])->middleware('permission:catalogs.bank.view')->name('catalogs.bank.index');
    Route::get('/catalogs/bank/create', [\App\Http\Controllers\BankController::class, 'create'])->middleware('permission:catalogs.bank.create')->name('catalogs.bank.create');
    Route::post('/catalogs/bank', [\App\Http\Controllers\BankController::class, 'store'])->middleware('permission:catalogs.bank.create')->name('catalogs.bank.store');
    Route::get('/catalogs/bank/export', [\App\Http\Controllers\BankController::class, 'export'])->middleware('permission:catalogs.bank.export')->name('catalogs.bank.export');
    Route::post('/catalogs/bank/bulk', [\App\Http\Controllers\BankController::class, 'bulk'])->middleware('permission:catalogs.bank.delete|catalogs.bank.restore|catalogs.bank.forceDelete|catalogs.bank.setActive')->name('catalogs.bank.bulk');
    Route::get('/catalogs/bank/selected', [\App\Http\Controllers\BankController::class, 'selected'])->middleware('permission:catalogs.bank.view')->name('catalogs.bank.selected');
    Route::get('/catalogs/bank/{bank}', [\App\Http\Controllers\BankController::class, 'show'])->middleware('permission:catalogs.bank.view')->name('catalogs.bank.show');
    Route::get('/catalogs/bank/{bank}/edit', [\App\Http\Controllers\BankController::class, 'edit'])->middleware('permission:catalogs.bank.update')->name('catalogs.bank.edit');
    Route::put('/catalogs/bank/{bank}', [\App\Http\Controllers\BankController::class, 'update'])->middleware('permission:catalogs.bank.update')->name('catalogs.bank.update');
    Route::patch('/catalogs/bank/{bank}/active', [\App\Http\Controllers\BankController::class, 'setActive'])->middleware('permission:catalogs.bank.setActive')->name('catalogs.bank.setActive');
    Route::delete('/catalogs/bank/{bank}', [\App\Http\Controllers\BankController::class, 'destroy'])->middleware('permission:catalogs.bank.delete')->name('catalogs.bank.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/phone-area-code', [\App\Http\Controllers\PhoneAreaCodeController::class, 'index'])->middleware('permission:catalogs.phone-area-code.view')->name('catalogs.phone-area-code.index');
    Route::get('/catalogs/phone-area-code/create', [\App\Http\Controllers\PhoneAreaCodeController::class, 'create'])->middleware('permission:catalogs.phone-area-code.create')->name('catalogs.phone-area-code.create');
    Route::post('/catalogs/phone-area-code', [\App\Http\Controllers\PhoneAreaCodeController::class, 'store'])->middleware('permission:catalogs.phone-area-code.create')->name('catalogs.phone-area-code.store');
    Route::get('/catalogs/phone-area-code/export', [\App\Http\Controllers\PhoneAreaCodeController::class, 'export'])->middleware('permission:catalogs.phone-area-code.export')->name('catalogs.phone-area-code.export');
    Route::post('/catalogs/phone-area-code/bulk', [\App\Http\Controllers\PhoneAreaCodeController::class, 'bulk'])->middleware('permission:catalogs.phone-area-code.delete|catalogs.phone-area-code.restore|catalogs.phone-area-code.forceDelete|catalogs.phone-area-code.setActive')->name('catalogs.phone-area-code.bulk');
    Route::get('/catalogs/phone-area-code/selected', [\App\Http\Controllers\PhoneAreaCodeController::class, 'selected'])->middleware('permission:catalogs.phone-area-code.view')->name('catalogs.phone-area-code.selected');
    Route::get('/catalogs/phone-area-code/{phone_area_code}', [\App\Http\Controllers\PhoneAreaCodeController::class, 'show'])->middleware('permission:catalogs.phone-area-code.view')->name('catalogs.phone-area-code.show');
    Route::get('/catalogs/phone-area-code/{phone_area_code}/edit', [\App\Http\Controllers\PhoneAreaCodeController::class, 'edit'])->middleware('permission:catalogs.phone-area-code.update')->name('catalogs.phone-area-code.edit');
    Route::put('/catalogs/phone-area-code/{phone_area_code}', [\App\Http\Controllers\PhoneAreaCodeController::class, 'update'])->middleware('permission:catalogs.phone-area-code.update')->name('catalogs.phone-area-code.update');
    Route::patch('/catalogs/phone-area-code/{phone_area_code}/active', [\App\Http\Controllers\PhoneAreaCodeController::class, 'setActive'])->middleware('permission:catalogs.phone-area-code.setActive')->name('catalogs.phone-area-code.setActive');
    Route::delete('/catalogs/phone-area-code/{phone_area_code}', [\App\Http\Controllers\PhoneAreaCodeController::class, 'destroy'])->middleware('permission:catalogs.phone-area-code.delete')->name('catalogs.phone-area-code.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/payment-type', [\App\Http\Controllers\PaymentTypeController::class, 'index'])->middleware('permission:catalogs.payment-type.view')->name('catalogs.payment-type.index');
    Route::get('/catalogs/payment-type/create', [\App\Http\Controllers\PaymentTypeController::class, 'create'])->middleware('permission:catalogs.payment-type.create')->name('catalogs.payment-type.create');
    Route::post('/catalogs/payment-type', [\App\Http\Controllers\PaymentTypeController::class, 'store'])->middleware('permission:catalogs.payment-type.create')->name('catalogs.payment-type.store');
    Route::get('/catalogs/payment-type/export', [\App\Http\Controllers\PaymentTypeController::class, 'export'])->middleware('permission:catalogs.payment-type.export')->name('catalogs.payment-type.export');
    Route::post('/catalogs/payment-type/bulk', [\App\Http\Controllers\PaymentTypeController::class, 'bulk'])->middleware('permission:catalogs.payment-type.delete|catalogs.payment-type.restore|catalogs.payment-type.forceDelete|catalogs.payment-type.setActive')->name('catalogs.payment-type.bulk');
    Route::get('/catalogs/payment-type/selected', [\App\Http\Controllers\PaymentTypeController::class, 'selected'])->middleware('permission:catalogs.payment-type.view')->name('catalogs.payment-type.selected');
    Route::get('/catalogs/payment-type/{payment_type}', [\App\Http\Controllers\PaymentTypeController::class, 'show'])->middleware('permission:catalogs.payment-type.view')->name('catalogs.payment-type.show');
    Route::get('/catalogs/payment-type/{payment_type}/edit', [\App\Http\Controllers\PaymentTypeController::class, 'edit'])->middleware('permission:catalogs.payment-type.update')->name('catalogs.payment-type.edit');
    Route::put('/catalogs/payment-type/{payment_type}', [\App\Http\Controllers\PaymentTypeController::class, 'update'])->middleware('permission:catalogs.payment-type.update')->name('catalogs.payment-type.update');
    Route::patch('/catalogs/payment-type/{payment_type}/active', [\App\Http\Controllers\PaymentTypeController::class, 'setActive'])->middleware('permission:catalogs.payment-type.setActive')->name('catalogs.payment-type.setActive');
    Route::delete('/catalogs/payment-type/{payment_type}', [\App\Http\Controllers\PaymentTypeController::class, 'destroy'])->middleware('permission:catalogs.payment-type.delete')->name('catalogs.payment-type.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/market', [\App\Http\Controllers\MarketController::class, 'index'])->middleware('permission:catalogs.market.view')->name('catalogs.market.index');
    Route::get('/catalogs/market/create', [\App\Http\Controllers\MarketController::class, 'create'])->middleware('permission:catalogs.market.create')->name('catalogs.market.create');
    Route::post('/catalogs/market', [\App\Http\Controllers\MarketController::class, 'store'])->middleware('permission:catalogs.market.create')->name('catalogs.market.store');
    Route::get('/catalogs/market/export', [\App\Http\Controllers\MarketController::class, 'export'])->middleware('permission:catalogs.market.export')->name('catalogs.market.export');
    Route::post('/catalogs/market/bulk', [\App\Http\Controllers\MarketController::class, 'bulk'])->middleware('permission:catalogs.market.delete|catalogs.market.restore|catalogs.market.forceDelete|catalogs.market.setActive')->name('catalogs.market.bulk');
    Route::get('/catalogs/market/selected', [\App\Http\Controllers\MarketController::class, 'selected'])->middleware('permission:catalogs.market.view')->name('catalogs.market.selected');
    Route::get('/catalogs/market/{market}', [\App\Http\Controllers\MarketController::class, 'show'])->middleware('permission:catalogs.market.view')->name('catalogs.market.show');
    Route::get('/catalogs/market/{market}/edit', [\App\Http\Controllers\MarketController::class, 'edit'])->middleware('permission:catalogs.market.update')->name('catalogs.market.edit');
    Route::put('/catalogs/market/{market}', [\App\Http\Controllers\MarketController::class, 'update'])->middleware('permission:catalogs.market.update')->name('catalogs.market.update');
    Route::patch('/catalogs/market/{market}/active', [\App\Http\Controllers\MarketController::class, 'setActive'])->middleware('permission:catalogs.market.setActive')->name('catalogs.market.setActive');
    Route::delete('/catalogs/market/{market}', [\App\Http\Controllers\MarketController::class, 'destroy'])->middleware('permission:catalogs.market.delete')->name('catalogs.market.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/local-location', [\App\Http\Controllers\LocalLocationController::class, 'index'])->middleware('permission:catalogs.local-location.view')->name('catalogs.local-location.index');
    Route::get('/catalogs/local-location/create', [\App\Http\Controllers\LocalLocationController::class, 'create'])->middleware('permission:catalogs.local-location.create')->name('catalogs.local-location.create');
    Route::post('/catalogs/local-location', [\App\Http\Controllers\LocalLocationController::class, 'store'])->middleware('permission:catalogs.local-location.create')->name('catalogs.local-location.store');
    Route::get('/catalogs/local-location/export', [\App\Http\Controllers\LocalLocationController::class, 'export'])->middleware('permission:catalogs.local-location.export')->name('catalogs.local-location.export');
    Route::post('/catalogs/local-location/bulk', [\App\Http\Controllers\LocalLocationController::class, 'bulk'])->middleware('permission:catalogs.local-location.delete|catalogs.local-location.restore|catalogs.local-location.forceDelete|catalogs.local-location.setActive')->name('catalogs.local-location.bulk');
    Route::get('/catalogs/local-location/selected', [\App\Http\Controllers\LocalLocationController::class, 'selected'])->middleware('permission:catalogs.local-location.view')->name('catalogs.local-location.selected');
    Route::get('/catalogs/local-location/{local_location}', [\App\Http\Controllers\LocalLocationController::class, 'show'])->middleware('permission:catalogs.local-location.view')->name('catalogs.local-location.show');
    Route::get('/catalogs/local-location/{local_location}/edit', [\App\Http\Controllers\LocalLocationController::class, 'edit'])->middleware('permission:catalogs.local-location.update')->name('catalogs.local-location.edit');
    Route::put('/catalogs/local-location/{local_location}', [\App\Http\Controllers\LocalLocationController::class, 'update'])->middleware('permission:catalogs.local-location.update')->name('catalogs.local-location.update');
    Route::patch('/catalogs/local-location/{local_location}/active', [\App\Http\Controllers\LocalLocationController::class, 'setActive'])->middleware('permission:catalogs.local-location.setActive')->name('catalogs.local-location.setActive');
    Route::delete('/catalogs/local-location/{local_location}', [\App\Http\Controllers\LocalLocationController::class, 'destroy'])->middleware('permission:catalogs.local-location.delete')->name('catalogs.local-location.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/local', [\App\Http\Controllers\LocalController::class, 'index'])->middleware('permission:catalogs.local.view')->name('catalogs.local.index');
    Route::get('/catalogs/local/create', [\App\Http\Controllers\LocalController::class, 'create'])->middleware('permission:catalogs.local.create')->name('catalogs.local.create');
    Route::post('/catalogs/local', [\App\Http\Controllers\LocalController::class, 'store'])->middleware('permission:catalogs.local.create')->name('catalogs.local.store');
    Route::get('/catalogs/local/export', [\App\Http\Controllers\LocalController::class, 'export'])->middleware('permission:catalogs.local.export')->name('catalogs.local.export');
    Route::post('/catalogs/local/bulk', [\App\Http\Controllers\LocalController::class, 'bulk'])->middleware('permission:catalogs.local.delete|catalogs.local.restore|catalogs.local.forceDelete|catalogs.local.setActive')->name('catalogs.local.bulk');
    Route::get('/catalogs/local/selected', [\App\Http\Controllers\LocalController::class, 'selected'])->middleware('permission:catalogs.local.view')->name('catalogs.local.selected');
    Route::get('/catalogs/local/{local}', [\App\Http\Controllers\LocalController::class, 'show'])->middleware('permission:catalogs.local.view')->name('catalogs.local.show');
    Route::get('/catalogs/local/{local}/edit', [\App\Http\Controllers\LocalController::class, 'edit'])->middleware('permission:catalogs.local.update')->name('catalogs.local.edit');
    Route::put('/catalogs/local/{local}', [\App\Http\Controllers\LocalController::class, 'update'])->middleware('permission:catalogs.local.update')->name('catalogs.local.update');
    Route::patch('/catalogs/local/{local}/active', [\App\Http\Controllers\LocalController::class, 'setActive'])->middleware('permission:catalogs.local.setActive')->name('catalogs.local.setActive');
    Route::delete('/catalogs/local/{local}', [\App\Http\Controllers\LocalController::class, 'destroy'])->middleware('permission:catalogs.local.delete')->name('catalogs.local.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/concessionaire', [\App\Http\Controllers\ConcessionaireController::class, 'index'])->middleware('permission:catalogs.concessionaire.view')->name('catalogs.concessionaire.index');
    Route::get('/catalogs/concessionaire/create', [\App\Http\Controllers\ConcessionaireController::class, 'create'])->middleware('permission:catalogs.concessionaire.create')->name('catalogs.concessionaire.create');
    Route::post('/catalogs/concessionaire', [\App\Http\Controllers\ConcessionaireController::class, 'store'])->middleware('permission:catalogs.concessionaire.create')->name('catalogs.concessionaire.store');
    Route::get('/catalogs/concessionaire/export', [\App\Http\Controllers\ConcessionaireController::class, 'export'])->middleware('permission:catalogs.concessionaire.export')->name('catalogs.concessionaire.export');
    Route::post('/catalogs/concessionaire/bulk', [\App\Http\Controllers\ConcessionaireController::class, 'bulk'])->middleware('permission:catalogs.concessionaire.delete|catalogs.concessionaire.restore|catalogs.concessionaire.forceDelete|catalogs.concessionaire.setActive')->name('catalogs.concessionaire.bulk');
    Route::get('/catalogs/concessionaire/selected', [\App\Http\Controllers\ConcessionaireController::class, 'selected'])->middleware('permission:catalogs.concessionaire.view')->name('catalogs.concessionaire.selected');
    Route::get('/catalogs/concessionaire/{concessionaire}', [\App\Http\Controllers\ConcessionaireController::class, 'show'])->middleware('permission:catalogs.concessionaire.view')->name('catalogs.concessionaire.show');
    Route::get('/catalogs/concessionaire/{concessionaire}/edit', [\App\Http\Controllers\ConcessionaireController::class, 'edit'])->middleware('permission:catalogs.concessionaire.update')->name('catalogs.concessionaire.edit');
    Route::put('/catalogs/concessionaire/{concessionaire}', [\App\Http\Controllers\ConcessionaireController::class, 'update'])->middleware('permission:catalogs.concessionaire.update')->name('catalogs.concessionaire.update');
    Route::post('/catalogs/concessionaire/{concessionaire}/portal-users', [\App\Http\Controllers\ConcessionaireController::class, 'invitePortalUser'])->middleware(['permission:catalogs.concessionaire.update', 'throttle:5,1'])->name('catalogs.concessionaire.portal-users');
    Route::post('/catalogs/concessionaire/{concessionaire}/portal-users/reset', [\App\Http\Controllers\ConcessionaireController::class, 'resetPortalUser'])->middleware(['permission:catalogs.concessionaire.update', 'throttle:5,1'])->name('catalogs.concessionaire.portal-users.reset');
    Route::patch('/catalogs/concessionaire/{concessionaire}/active', [\App\Http\Controllers\ConcessionaireController::class, 'setActive'])->middleware('permission:catalogs.concessionaire.setActive')->name('catalogs.concessionaire.setActive');
    Route::delete('/catalogs/concessionaire/{concessionaire}', [\App\Http\Controllers\ConcessionaireController::class, 'destroy'])->middleware('permission:catalogs.concessionaire.delete')->name('catalogs.concessionaire.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/contract', [\App\Http\Controllers\ContractController::class, 'index'])->middleware('permission:catalogs.contract.view')->name('catalogs.contract.index');
    Route::get('/catalogs/contract/create', [\App\Http\Controllers\ContractController::class, 'create'])->middleware('permission:catalogs.contract.create')->name('catalogs.contract.create');
    Route::post('/catalogs/contract', [\App\Http\Controllers\ContractController::class, 'store'])->middleware('permission:catalogs.contract.create')->name('catalogs.contract.store');
    Route::get('/catalogs/contract/export', [\App\Http\Controllers\ContractController::class, 'export'])->middleware('permission:catalogs.contract.export')->name('catalogs.contract.export');
    Route::post('/catalogs/contract/bulk', [\App\Http\Controllers\ContractController::class, 'bulk'])->middleware('permission:catalogs.contract.delete|catalogs.contract.restore|catalogs.contract.forceDelete|catalogs.contract.setActive|catalogs.contract.update')->name('catalogs.contract.bulk');
    Route::get('/catalogs/contract/selected', [\App\Http\Controllers\ContractController::class, 'selected'])->middleware('permission:catalogs.contract.view')->name('catalogs.contract.selected');
    Route::get('/catalogs/contract/{contract}', [\App\Http\Controllers\ContractController::class, 'show'])->middleware('permission:catalogs.contract.view')->name('catalogs.contract.show');
    Route::get('/catalogs/contract/{contract}/download', [\App\Http\Controllers\ContractController::class, 'downloadPdf'])
        ->middleware('permission:catalogs.contract.view')
        ->name('catalogs.contract.download');
    Route::get('/catalogs/contract/{contract}/edit', [\App\Http\Controllers\ContractController::class, 'edit'])->middleware('permission:catalogs.contract.update')->name('catalogs.contract.edit');
    Route::put('/catalogs/contract/{contract}', [\App\Http\Controllers\ContractController::class, 'update'])->middleware('permission:catalogs.contract.update')->name('catalogs.contract.update');
    Route::patch('/catalogs/contract/{contract}/active', [\App\Http\Controllers\ContractController::class, 'setActive'])->middleware('permission:catalogs.contract.setActive')->name('catalogs.contract.setActive');
    Route::patch('/catalogs/contract/{contract}/confirm', [\App\Http\Controllers\ContractController::class, 'confirm'])->middleware('permission:catalogs.contract.update')->name('catalogs.contract.confirm');
    Route::patch('/catalogs/contract/{contract}/terminate', [\App\Http\Controllers\ContractController::class, 'terminate'])->middleware('permission:catalogs.contract.update')->name('catalogs.contract.terminate');
    Route::post('/catalogs/contract/{contract}/extend', [\App\Http\Controllers\ContractController::class, 'extend'])->middleware('permission:catalogs.contract.update')->name('catalogs.contract.extend');
    Route::patch('/catalogs/contract/{contract}/sign', [\App\Http\Controllers\ContractController::class, 'sign'])->middleware('permission:catalogs.contract.update')->name('catalogs.contract.sign');
    Route::get('/catalogs/contract/{contract}/extensions/{extension}/download', [\App\Http\Controllers\ContractController::class, 'downloadExtension'])
        ->middleware('permission:catalogs.contract.view')
        ->name('catalogs.contract.extension.download');
    Route::delete('/catalogs/contract/{contract}', [\App\Http\Controllers\ContractController::class, 'destroy'])->middleware('permission:catalogs.contract.delete')->name('catalogs.contract.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/market-tariff', [\App\Http\Controllers\MarketTariffController::class, 'index'])->middleware('permission:catalogs.market-tariff.view')->name('catalogs.market-tariff.index');
    Route::get('/catalogs/market-tariff/create', [\App\Http\Controllers\MarketTariffController::class, 'create'])->middleware('permission:catalogs.market-tariff.create')->name('catalogs.market-tariff.create');
    Route::post('/catalogs/market-tariff', [\App\Http\Controllers\MarketTariffController::class, 'store'])->middleware('permission:catalogs.market-tariff.create')->name('catalogs.market-tariff.store');
    Route::get('/catalogs/market-tariff/export', [\App\Http\Controllers\MarketTariffController::class, 'export'])->middleware('permission:catalogs.market-tariff.export')->name('catalogs.market-tariff.export');
    Route::post('/catalogs/market-tariff/bulk', [\App\Http\Controllers\MarketTariffController::class, 'bulk'])->middleware('permission:catalogs.market-tariff.delete|catalogs.market-tariff.restore|catalogs.market-tariff.forceDelete|catalogs.market-tariff.setActive')->name('catalogs.market-tariff.bulk');
    Route::get('/catalogs/market-tariff/selected', [\App\Http\Controllers\MarketTariffController::class, 'selected'])->middleware('permission:catalogs.market-tariff.view')->name('catalogs.market-tariff.selected');
    Route::get('/catalogs/market-tariff/{market_tariff}', [\App\Http\Controllers\MarketTariffController::class, 'show'])->middleware('permission:catalogs.market-tariff.view')->name('catalogs.market-tariff.show');
    Route::get('/catalogs/market-tariff/{market_tariff}/edit', [\App\Http\Controllers\MarketTariffController::class, 'edit'])->middleware('permission:catalogs.market-tariff.update')->name('catalogs.market-tariff.edit');
    Route::put('/catalogs/market-tariff/{market_tariff}', [\App\Http\Controllers\MarketTariffController::class, 'update'])->middleware('permission:catalogs.market-tariff.update')->name('catalogs.market-tariff.update');
    Route::patch('/catalogs/market-tariff/{market_tariff}/active', [\App\Http\Controllers\MarketTariffController::class, 'setActive'])->middleware('permission:catalogs.market-tariff.setActive')->name('catalogs.market-tariff.setActive');
    Route::delete('/catalogs/market-tariff/{market_tariff}', [\App\Http\Controllers\MarketTariffController::class, 'destroy'])->middleware('permission:catalogs.market-tariff.delete')->name('catalogs.market-tariff.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/charge-status', [\App\Http\Controllers\ChargeStatusController::class, 'index'])->middleware('permission:catalogs.charge-status.view')->name('catalogs.charge-status.index');
    Route::get('/catalogs/charge-status/create', [\App\Http\Controllers\ChargeStatusController::class, 'create'])->middleware('permission:catalogs.charge-status.create')->name('catalogs.charge-status.create');
    Route::post('/catalogs/charge-status', [\App\Http\Controllers\ChargeStatusController::class, 'store'])->middleware('permission:catalogs.charge-status.create')->name('catalogs.charge-status.store');
    Route::get('/catalogs/charge-status/export', [\App\Http\Controllers\ChargeStatusController::class, 'export'])->middleware('permission:catalogs.charge-status.export')->name('catalogs.charge-status.export');
    Route::post('/catalogs/charge-status/bulk', [\App\Http\Controllers\ChargeStatusController::class, 'bulk'])->middleware('permission:catalogs.charge-status.delete|catalogs.charge-status.restore|catalogs.charge-status.forceDelete|catalogs.charge-status.setActive')->name('catalogs.charge-status.bulk');
    Route::get('/catalogs/charge-status/selected', [\App\Http\Controllers\ChargeStatusController::class, 'selected'])->middleware('permission:catalogs.charge-status.view')->name('catalogs.charge-status.selected');
    Route::get('/catalogs/charge-status/{charge_status}', [\App\Http\Controllers\ChargeStatusController::class, 'show'])->middleware('permission:catalogs.charge-status.view')->name('catalogs.charge-status.show');
    Route::get('/catalogs/charge-status/{charge_status}/edit', [\App\Http\Controllers\ChargeStatusController::class, 'edit'])->middleware('permission:catalogs.charge-status.update')->name('catalogs.charge-status.edit');
    Route::put('/catalogs/charge-status/{charge_status}', [\App\Http\Controllers\ChargeStatusController::class, 'update'])->middleware('permission:catalogs.charge-status.update')->name('catalogs.charge-status.update');
    Route::patch('/catalogs/charge-status/{charge_status}/active', [\App\Http\Controllers\ChargeStatusController::class, 'setActive'])->middleware('permission:catalogs.charge-status.setActive')->name('catalogs.charge-status.setActive');
    Route::delete('/catalogs/charge-status/{charge_status}', [\App\Http\Controllers\ChargeStatusController::class, 'destroy'])->middleware('permission:catalogs.charge-status.delete')->name('catalogs.charge-status.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/debt-transfer-reason', [\App\Http\Controllers\DebtTransferReasonController::class, 'index'])->middleware('permission:catalogs.debt-transfer-reason.view')->name('catalogs.debt-transfer-reason.index');
    Route::get('/catalogs/debt-transfer-reason/create', [\App\Http\Controllers\DebtTransferReasonController::class, 'create'])->middleware('permission:catalogs.debt-transfer-reason.create')->name('catalogs.debt-transfer-reason.create');
    Route::post('/catalogs/debt-transfer-reason', [\App\Http\Controllers\DebtTransferReasonController::class, 'store'])->middleware('permission:catalogs.debt-transfer-reason.create')->name('catalogs.debt-transfer-reason.store');
    Route::get('/catalogs/debt-transfer-reason/export', [\App\Http\Controllers\DebtTransferReasonController::class, 'export'])->middleware('permission:catalogs.debt-transfer-reason.export')->name('catalogs.debt-transfer-reason.export');
    Route::post('/catalogs/debt-transfer-reason/bulk', [\App\Http\Controllers\DebtTransferReasonController::class, 'bulk'])->middleware('permission:catalogs.debt-transfer-reason.delete|catalogs.debt-transfer-reason.restore|catalogs.debt-transfer-reason.forceDelete|catalogs.debt-transfer-reason.setActive')->name('catalogs.debt-transfer-reason.bulk');
    Route::get('/catalogs/debt-transfer-reason/selected', [\App\Http\Controllers\DebtTransferReasonController::class, 'selected'])->middleware('permission:catalogs.debt-transfer-reason.view')->name('catalogs.debt-transfer-reason.selected');
    Route::get('/catalogs/debt-transfer-reason/{debt_transfer_reason}', [\App\Http\Controllers\DebtTransferReasonController::class, 'show'])->middleware('permission:catalogs.debt-transfer-reason.view')->name('catalogs.debt-transfer-reason.show');
    Route::get('/catalogs/debt-transfer-reason/{debt_transfer_reason}/edit', [\App\Http\Controllers\DebtTransferReasonController::class, 'edit'])->middleware('permission:catalogs.debt-transfer-reason.update')->name('catalogs.debt-transfer-reason.edit');
    Route::put('/catalogs/debt-transfer-reason/{debt_transfer_reason}', [\App\Http\Controllers\DebtTransferReasonController::class, 'update'])->middleware('permission:catalogs.debt-transfer-reason.update')->name('catalogs.debt-transfer-reason.update');
    Route::patch('/catalogs/debt-transfer-reason/{debt_transfer_reason}/active', [\App\Http\Controllers\DebtTransferReasonController::class, 'setActive'])->middleware('permission:catalogs.debt-transfer-reason.setActive')->name('catalogs.debt-transfer-reason.setActive');
    Route::delete('/catalogs/debt-transfer-reason/{debt_transfer_reason}', [\App\Http\Controllers\DebtTransferReasonController::class, 'destroy'])->middleware('permission:catalogs.debt-transfer-reason.delete')->name('catalogs.debt-transfer-reason.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/fx-rate', [\App\Http\Controllers\FxRateController::class, 'index'])->middleware('permission:catalogs.fx-rate.view')->name('catalogs.fx-rate.index');
    Route::get('/catalogs/fx-rate/create', [\App\Http\Controllers\FxRateController::class, 'create'])->middleware('permission:catalogs.fx-rate.create')->name('catalogs.fx-rate.create');
    Route::post('/catalogs/fx-rate', [\App\Http\Controllers\FxRateController::class, 'store'])->middleware('permission:catalogs.fx-rate.create')->name('catalogs.fx-rate.store');
    Route::get('/catalogs/fx-rate/export', [\App\Http\Controllers\FxRateController::class, 'export'])->middleware('permission:catalogs.fx-rate.export')->name('catalogs.fx-rate.export');
    Route::post('/catalogs/fx-rate/sync', [\App\Http\Controllers\FxRateController::class, 'sync'])->middleware('permission:catalogs.fx-rate.update')->name('catalogs.fx-rate.sync');
    Route::post('/catalogs/fx-rate/bulk', [\App\Http\Controllers\FxRateController::class, 'bulk'])->middleware('permission:catalogs.fx-rate.delete|catalogs.fx-rate.restore|catalogs.fx-rate.forceDelete|catalogs.fx-rate.setActive')->name('catalogs.fx-rate.bulk');
    Route::get('/catalogs/fx-rate/selected', [\App\Http\Controllers\FxRateController::class, 'selected'])->middleware('permission:catalogs.fx-rate.view')->name('catalogs.fx-rate.selected');
    Route::get('/catalogs/fx-rate/{fx_rate}', [\App\Http\Controllers\FxRateController::class, 'show'])->middleware('permission:catalogs.fx-rate.view')->name('catalogs.fx-rate.show');
    Route::get('/catalogs/fx-rate/{fx_rate}/edit', [\App\Http\Controllers\FxRateController::class, 'edit'])->middleware('permission:catalogs.fx-rate.update')->name('catalogs.fx-rate.edit');
    Route::put('/catalogs/fx-rate/{fx_rate}', [\App\Http\Controllers\FxRateController::class, 'update'])->middleware('permission:catalogs.fx-rate.update')->name('catalogs.fx-rate.update');
    Route::patch('/catalogs/fx-rate/{fx_rate}/active', [\App\Http\Controllers\FxRateController::class, 'setActive'])->middleware('permission:catalogs.fx-rate.setActive')->name('catalogs.fx-rate.setActive');
    Route::delete('/catalogs/fx-rate/{fx_rate}', [\App\Http\Controllers\FxRateController::class, 'destroy'])->middleware('permission:catalogs.fx-rate.delete')->name('catalogs.fx-rate.destroy');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/catalogs/company-bank-account', [\App\Http\Controllers\CompanyBankAccountController::class, 'index'])->middleware('permission:catalogs.company-bank-account.view')->name('catalogs.company-bank-account.index');
    Route::get('/catalogs/company-bank-account/create', [\App\Http\Controllers\CompanyBankAccountController::class, 'create'])->middleware('permission:catalogs.company-bank-account.create')->name('catalogs.company-bank-account.create');
    Route::post('/catalogs/company-bank-account', [\App\Http\Controllers\CompanyBankAccountController::class, 'store'])->middleware('permission:catalogs.company-bank-account.create')->name('catalogs.company-bank-account.store');
    Route::get('/catalogs/company-bank-account/export', [\App\Http\Controllers\CompanyBankAccountController::class, 'export'])->middleware('permission:catalogs.company-bank-account.export')->name('catalogs.company-bank-account.export');
    Route::post('/catalogs/company-bank-account/bulk', [\App\Http\Controllers\CompanyBankAccountController::class, 'bulk'])->middleware('permission:catalogs.company-bank-account.delete|catalogs.company-bank-account.restore|catalogs.company-bank-account.forceDelete|catalogs.company-bank-account.setActive')->name('catalogs.company-bank-account.bulk');
    Route::get('/catalogs/company-bank-account/selected', [\App\Http\Controllers\CompanyBankAccountController::class, 'selected'])->middleware('permission:catalogs.company-bank-account.view')->name('catalogs.company-bank-account.selected');
    Route::get('/catalogs/company-bank-account/{company_bank_account}', [\App\Http\Controllers\CompanyBankAccountController::class, 'show'])->middleware('permission:catalogs.company-bank-account.view')->name('catalogs.company-bank-account.show');
    Route::get('/catalogs/company-bank-account/{company_bank_account}/edit', [\App\Http\Controllers\CompanyBankAccountController::class, 'edit'])->middleware('permission:catalogs.company-bank-account.update')->name('catalogs.company-bank-account.edit');
    Route::put('/catalogs/company-bank-account/{company_bank_account}', [\App\Http\Controllers\CompanyBankAccountController::class, 'update'])->middleware('permission:catalogs.company-bank-account.update')->name('catalogs.company-bank-account.update');
    Route::patch('/catalogs/company-bank-account/{company_bank_account}/active', [\App\Http\Controllers\CompanyBankAccountController::class, 'setActive'])->middleware('permission:catalogs.company-bank-account.setActive')->name('catalogs.company-bank-account.setActive');
    Route::delete('/catalogs/company-bank-account/{company_bank_account}', [\App\Http\Controllers\CompanyBankAccountController::class, 'destroy'])->middleware('permission:catalogs.company-bank-account.delete')->name('catalogs.company-bank-account.destroy');
});

// Marker: END AUTO-GENERATED CATALOG ROUTES (make:catalog)
