<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * CompanyBankAccount model generated by make:catalog
 *
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\CompanyBankAccount>>
 *
 * @phpstan-use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\CompanyBankAccount>>
 *
 * @method static \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\CompanyBankAccount> factory($count = null, $state = [])
 */
class CompanyBankAccount extends Model implements AuditableContract
{
    use AuditableTrait, HasFactory, SoftDeletes;

    protected $table = 'company_bank_accounts';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'bank_id',
        'account_number',
        'phone_number',
        'account_holder_name',
        'document_type',
        'document_number',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
        ];
    }

    /**
     * Banco asociado a la cuenta receptora.
     */
    /**
     * @return BelongsTo<\App\Models\Bank, self>
     */
    public function bank(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Bank::class);
    }
}
