<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Concessionaire model generated by make:catalog
 *
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<self>>
 */
class Concessionaire extends Model implements AuditableContract
{
    use AuditableTrait;

    /** @use HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<self>> */
    use HasFactory;

    use SoftDeletes;

    protected $table = 'concessionaires';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'concessionaire_type_id',
        'full_name',
        'document_type_id',
        'document_number',
        'fiscal_address',
        'email',
        'phone_area_code_id',
        'phone_number',
        'photo_path',
        'id_document_path',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
        ];
    }

    /**
     * Relationships
     */
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\ConcessionaireType, static>
     */
    public function concessionaireType(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(ConcessionaireType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\DocumentType, static>
     */
    public function documentType(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(DocumentType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\PhoneAreaCode, static>
     */
    public function phoneAreaCode(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(PhoneAreaCode::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany<\App\Models\Contract, \App\Models\Concessionaire>
     */
    public function contracts(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Contract::class, 'concessionaire_contract')
            ->withTimestamps()
            ->withPivot('is_primary');
    }

    /**
     * @return BelongsToMany<\App\Models\User, self>
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'concessionaire_user')
            ->withTimestamps()
            ->withPivot(['is_primary', 'status', 'invited_at', 'accepted_at', 'created_by']);
    }
}
