<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Contract model generated by make:catalog
 *
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Database\Factories\ContractFactory>
 */
class Contract extends Model implements AuditableContract
{
    use AuditableTrait;

    /** @use HasFactory<\Database\Factories\ContractFactory> */
    use HasFactory;

    use SoftDeletes;

    protected $table = 'contracts';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'number',
        'contract_type_id',
        'contract_status_id',
        'contract_modality_id',
        'trade_category_id',
        'start_date',
        'end_date',
        'billing_day',
        'monthly_price_eur',
        'pdf_path',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'start_date' => 'date',
            'end_date' => 'date',
            'billing_day' => 'integer',
            'monthly_price_eur' => 'decimal:2',
            'signed_at' => 'datetime',
            'is_active' => 'boolean',
        ];
    }

    /**
     * Relationships
     */
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\ContractType, static>
     */
    public function type(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(ContractType::class, 'contract_type_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\ContractStatus, static>
     */
    public function status(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(ContractStatus::class, 'contract_status_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\ContractModality, static>
     */
    public function modality(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(ContractModality::class, 'contract_modality_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\TradeCategory, static>
     */
    public function tradeCategory(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(TradeCategory::class, 'trade_category_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany<\App\Models\Concessionaire, \App\Models\Contract>
     */
    public function concessionaires(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Concessionaire::class, 'concessionaire_contract')
            ->withTimestamps()
            ->withPivot('is_primary');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany<\App\Models\Local, \App\Models\Contract>
     */
    public function locals(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Local::class, 'contract_local')->withTimestamps();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\ContractExtension, \App\Models\Contract>
     */
    public function extensions(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(ContractExtension::class, 'contract_id');
    }
}
