<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * DocumentType model generated by make:catalog
 *
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\DocumentType>>
 */
class DocumentType extends Model implements AuditableContract
{
    /** @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\DocumentType>> */
    use AuditableTrait, HasFactory, SoftDeletes;

    protected $table = 'document_types';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'code',
        'name',
        'mask',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
        ];
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\Concessionaire, self>
     */
    public function concessionaires(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Concessionaire::class);
    }
}
