<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * FxRate model generated by make:catalog
 */
/**
 * @phpstan-use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\FxRate>>
 */
class FxRate extends Model implements AuditableContract
{
    use AuditableTrait, HasFactory, SoftDeletes;

    protected $table = 'fx_rates';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'currency_code',
        'rate_date',
        'value_date',
        'published_at',
        'rate_to_ves',
        'operational_from',
        'operational_to',
        'source',
        'is_official',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_official' => 'boolean',
            'is_active' => 'boolean',
        ];
    }
}
