<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * LocalStatus model generated by make:catalog
 *
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\LocalStatus>>
 */
class LocalStatus extends Model implements AuditableContract
{
    /** @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\LocalStatus>> */
    use AuditableTrait, HasFactory, SoftDeletes;

    protected $table = 'local_statuses';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'code',
        'name',
        'description',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
        ];
    }

    /**
     * Relationships
     */
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\Local, \App\Models\LocalStatus>
     */
    public function locals(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Local::class);
    }
}
