<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Local model generated by make:catalog
 *
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Local>>
 */
class Local extends Model implements AuditableContract
{
    use AuditableTrait, HasFactory, SoftDeletes;

    protected $table = 'locals';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'code',
        'name',
        'market_id',
        'local_type_id',
        'local_status_id',
        'local_location_id',
        'area_m2',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'market_id' => 'integer',
            'local_type_id' => 'integer',
            'local_status_id' => 'integer',
            'local_location_id' => 'integer',
            'area_m2' => 'decimal:2',
            'is_active' => 'boolean',
        ];
    }

    /**
     * Relationships
     */
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\Market, static>
     */
    public function market(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Market::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\LocalType, static>
     */
    public function localType(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(LocalType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\LocalStatus, static>
     */
    public function localStatus(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(LocalStatus::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo<\App\Models\LocalLocation, static>
     */
    public function localLocation(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(LocalLocation::class);
    }
}
