<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * MarketTariff model generated by make:catalog
 */
/**
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\MarketTariff>>
 */
class MarketTariff extends Model implements AuditableContract
{
    /** @use HasFactory<Factory<self>> */
    use AuditableTrait, HasFactory, SoftDeletes;

    protected $table = 'market_tariffs';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'market_id',
        'valid_from',
        'price_per_m2_eur_minor',
        'is_current',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_current' => 'boolean',
            'is_active' => 'boolean',
        ];
    }
}
