<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

/**
 * Payment model generated by make:catalog
 *
 * @use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Payment>>
 *
 * @phpstan-use \Illuminate\Database\Eloquent\Factories\HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Payment>>
 *
 * @method static \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Payment> factory($count = null, $state = [])
 */
class Payment extends Model implements AuditableContract
{
    use AuditableTrait, HasFactory, SoftDeletes;

    protected $table = 'payments';

    protected static function booted(): void
    {
        static::creating(function (Payment $model): void {
            // Map method -> payment_type_id if missing
            $ptId = $model->getAttribute('payment_type_id');
            $methodCode = (string) ($model->getAttribute('method') ?? '');
            if (($ptId === null || (int) $ptId === 0) && $methodCode !== '') {
                $code = strtoupper(trim($methodCode));
                $normalized = match ($code) {
                    'TRANSFER' => 'TRF',
                    'PAGOMOVIL', 'PAGO MOVIL', 'PAGO-MOVIL' => 'PMOV',
                    default => $code,
                };
                try {
                    /** @var null|\App\Models\PaymentType $pt */
                    $pt = \App\Models\PaymentType::query()->where('code', $normalized)->first();
                    if (! $pt) {
                        $pt = \App\Models\PaymentType::query()->create([
                            'code' => $normalized,
                            'name' => $normalized,
                            'is_active' => true,
                        ]);
                    }
                    $model->setAttribute('payment_type_id', (int) $pt->getKey());
                } catch (\Throwable $e) {
                    // ignore; validation may catch later
                }
            }

            // Map payer_document_type -> payer_document_type_id if missing
            $pdtId = $model->getAttribute('payer_document_type_id');
            $docCode = (string) ($model->getAttribute('payer_document_type') ?? '');
            if (($pdtId === null || (int) $pdtId === 0) && $docCode !== '') {
                $code = strtoupper(trim($docCode));
                try {
                    /** @var null|\App\Models\DocumentType $dt */
                    $dt = \App\Models\DocumentType::query()->where('code', $code)->first();
                    if (! $dt) {
                        $dt = \App\Models\DocumentType::query()->create([
                            'code' => $code,
                            'name' => $code,
                            'is_active' => true,
                        ]);
                    }
                    $model->setAttribute('payer_document_type_id', (int) $dt->getKey());
                } catch (\Throwable $e) {
                    // ignore
                }
            }
        });
    }

    /**
     * @var list<string>
     */
    protected $fillable = [
        'local_id',
        'debtor_type',
        'debtor_id',
        'company_bank_account_id',
        // Virtual inputs accepted for BC compatibility; mapped to FK via mutators below
        'method',
        'payment_type_id',
        'origin_bank_id',
        'payer_document_type',
        'payer_document_type_id',
        'payer_document_number',
        'payer_account_number',
        'payer_phone_e164',
        'reference',
        'amount_bs_minor',
        'paid_on',
        'fx_rate_id',
        'status',
        'gateway_request',
        'gateway_response',
        'gateway_resp_code',
        'gateway_message',
        'payer_details',
        'idempotency_key',
        'exoneration_reason',
        'voided_at',
        'voided_by_user_id',
        'void_reason',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'local_id' => 'integer',
            'debtor_id' => 'integer',
            'company_bank_account_id' => 'integer',
            'origin_bank_id' => 'integer',
            'payment_type_id' => 'integer',
            'payer_document_type_id' => 'integer',
            'amount_bs_minor' => 'integer',
            'fx_rate_id' => 'integer',
            'gateway_request' => 'array',
            'gateway_response' => 'array',
            'payer_details' => 'array',
            'voided_at' => 'datetime',
            'voided_by_user_id' => 'integer',
        ];
    }

    /**
     * @return BelongsTo<\App\Models\CompanyBankAccount, self>
     */
    public function companyBankAccount()
    {
        return $this->belongsTo(CompanyBankAccount::class);
    }

    public function paymentType(): BelongsTo
    {
        return $this->belongsTo(PaymentType::class);
    }

    public function payerDocumentType(): BelongsTo
    {
        return $this->belongsTo(DocumentType::class, 'payer_document_type_id');
    }

    /**
     * @return HasMany<\App\Models\PaymentAllocation, self>
     */
    public function allocations()
    {
        return $this->hasMany(PaymentAllocation::class);
    }

    /**
     * Banco de origen asociado al pago.
     *
     * @return BelongsTo<\App\Models\Bank, self>
     */
    public function originBank(): BelongsTo
    {
        return $this->belongsTo(Bank::class, 'origin_bank_id');
    }

    /**
     * Relación al catálogo de estatus de pago.
     *
     * @return BelongsTo<\App\Models\PaymentStatus, self>
     */
    public function paymentStatus(): BelongsTo
    {
        return $this->belongsTo(PaymentStatus::class);
    }

    /**
     * Accesor virtual 'status' para exponer una etiqueta estable (REGISTERED/CONFIRMED/APPLIED)
     * a partir del código del catálogo (REG/CONF/CONC).
     */
    public function getStatusAttribute(): ?string
    {
        // Resolver código desde la relación si está cargada; si no, consulta puntual por id
        $code = null;
        try {
            if ($this->relationLoaded('paymentStatus')) {
                /** @var null|\App\Models\PaymentStatus $rel */
                $rel = $this->getRelation('paymentStatus');
                $code = $rel?->getAttribute('code');
            } else {
                $psId = $this->getAttribute('payment_status_id');
                if ($psId) {
                    /** @var null|\App\Models\PaymentStatus $ps */
                    $ps = PaymentStatus::query()->find((int) $psId);
                    $code = $ps?->getAttribute('code');
                }
            }
        } catch (\Throwable $e) {
            // ignore
        }

        if (! is_string($code) || $code === '') {
            return null;
        }

        $map = [
            'REG' => 'REGISTERED',
            'CONF' => 'CONFIRMED',
            'CONC' => 'APPLIED',
            'VOID' => 'VOID',
        ];

        return $map[strtoupper($code)] ?? $code;
    }

    /**
     * Mutador virtual 'status' para permitir asignaciones con etiquetas de negocio
     * (REGISTERED/CONFIRMED/APPLIED) y reflejarlo en payment_status_id mediante el catálogo.
     *
     * @param  mixed  $value
     */
    public function setStatusAttribute($value): void
    {
        $val = is_string($value) ? strtoupper($value) : null;
        $uiToCode = [
            'REGISTERED' => 'REG',
            'CONFIRMED' => 'CONF',
            'APPLIED' => 'CONC',
            'VOID' => 'VOID',
            'VOIDED' => 'VOID',
        ];

        $code = $val ? ($uiToCode[$val] ?? $val) : null; // permite pasar directamente códigos REG/CONF/CONC
        $id = null;
        if ($code) {
            /** @var null|\App\Models\PaymentStatus $ps */
            $ps = PaymentStatus::query()->where('code', $code)->first();
            if ($ps) {
                $id = (int) $ps->getKey();
            }
        }

        $this->attributes['payment_status_id'] = $id;
    }

    /**
     * Virtual setter for legacy 'method' code. Maps to payment_type_id FK.
     * Accepts synonyms: TRANSFER -> TRF, PMOV variations -> PMOV.
     *
     * @param  mixed  $value
     */
    public function setMethodAttribute($value): void
    {
        $code = is_string($value) ? strtoupper(trim($value)) : null;
        if (! $code) {
            return;
        }
        $normalized = match ($code) {
            'TRANSFER' => 'TRF',
            'PAGOMOVIL', 'PAGO MOVIL', 'PAGO-MOVIL' => 'PMOV',
            default => $code,
        };
        try {
            /** @var null|\App\Models\PaymentType $pt */
            $pt = \App\Models\PaymentType::query()->where('code', $normalized)->first();
            if (! $pt) {
                // Create minimal catalog row if missing to satisfy FK during tests
                $pt = \App\Models\PaymentType::query()->create([
                    'code' => $normalized,
                    'name' => $normalized,
                    'is_active' => true,
                ]);
            }
            $this->attributes['payment_type_id'] = (int) $pt->getKey();
        } catch (\Throwable $e) {
            $this->attributes['payment_type_id'] = null;
        }
        // Persist normalized method code for compatibility
        $this->attributes['method'] = $normalized;
    }

    /**
     * Virtual setter for legacy 'payer_document_type' code (e.g., V/E/J/G).
     * Maps to payer_document_type_id FK.
     *
     * @param  mixed  $value
     */
    public function setPayerDocumentTypeAttribute($value): void
    {
        $code = is_string($value) ? strtoupper(trim($value)) : null;
        if (! $code) {
            return;
        }
        try {
            /** @var null|\App\Models\DocumentType $dt */
            $dt = \App\Models\DocumentType::query()->where('code', $code)->first();
            if (! $dt) {
                $dt = \App\Models\DocumentType::query()->create([
                    'code' => $code,
                    'name' => $code,
                    'is_active' => true,
                ]);
            }
            $this->attributes['payer_document_type_id'] = (int) $dt->getKey();
        } catch (\Throwable $e) {
            $this->attributes['payer_document_type_id'] = null;
        }
        // Do not persist 'payer_document_type' (no column)
    }
}
