name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, sqlite3, pdo_sqlite
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Prepare Laravel environment
        run: |
          cp .env.example .env || true
          echo -e "\nDB_CONNECTION=sqlite\nDB_DATABASE=database/database.sqlite" >> .env
          php -r "file_exists('database') || mkdir('database');"
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
          php artisan key:generate
      - name: Run migrations and seed
        run: php artisan migrate:fresh --seed
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install NPM dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
